package com.sgstt.entidad;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cliente generated by Luis Ballena
 */
@Entity
@Table(name = "cliente", catalog = "sgstt")
public class Cliente implements java.io.Serializable {
    private static final long serialVersionUID = 600842115606509566L;

    @Id
    @GeneratedValue
    @Column
    private int idCliente;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ID_TIPOCLIENTE",nullable = false)
    private TipoCliente tipoCliente;
    @Column
    private String nombre;
    @Column
    private Integer numeroDocumento;
    @Column
    private String direccion;
    @Column
    private Integer idEstado;
    @Column
    private String correo;

    public Cliente() {
    }

    public Cliente(int idCliente, TipoCliente tipoCliente) {
        this.idCliente = idCliente;
        this.tipoCliente = tipoCliente;
    }
    
    /* GETTERS AND SETTERS */
    
    public int getIdCliente() {
        return idCliente;
    }

    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    public TipoCliente getTipoCliente() {
        return tipoCliente;
    }

    public void setTipoCliente(TipoCliente tipoCliente) {
        this.tipoCliente = tipoCliente;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Integer getNumeroDocumento() {
        return numeroDocumento;
    }

    public void setNumeroDocumento(Integer numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public Integer getIdEstado() {
        return idEstado;
    }

    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }
    
}
